name: print-name

on:
  push:
    branches:
      - main

jobs:
  print_name_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print my name
        run: echo "Scaler Student"

